export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJKYXNtaW5lIFBhb2xpbmUgQXNpbW92IiwiZW1haWwiOiJqLnBhb2xpbmUuYXNpbW92QGdtYWlsLmNvbSIsImlhdCI6MTcyMTQ2NzU4OSwiZXhwIjoxNzIyMDcyMzg5LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMTMifQ.eyyXu8lAkLc42yD-Dyzyohu3abKhx8Jo5p64xGfAmqc';
